import org.springframework.boot.context.embedded.WebApplicationContextServletContextAwareProcessor;
public class FunctionUse733 {
public void funcUse() {
WebApplicationContextServletContextAwareProcessor webapplicationcontextservletcontextawareprocessor = new WebApplicationContextServletContextAwareProcessor();
webapplicationcontextservletcontextawareprocessor.getServletContext();
}
}