import org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext;
public class FunctionUse1181 {
public void funcUse() {
AnnotationConfigEmbeddedWebApplicationContext annotationconfigembeddedwebapplicationcontext = new AnnotationConfigEmbeddedWebApplicationContext();
annotationconfigembeddedwebapplicationcontext.setBeanNameGenerator(null);
}
}