import org.springframework.boot.context.embedded.InitParameterConfiguringServletContextInitializer;
public class FunctionUse800 {
public void funcUse() {
InitParameterConfiguringServletContextInitializer initparameterconfiguringservletcontextinitializer = new InitParameterConfiguringServletContextInitializer();
initparameterconfiguringservletcontextinitializer.onStartup(null);
}
}