import org.springframework.boot.env.SpringApplicationJsonEnvironmentPostProcessor;
public class FunctionUse1809 {
public void funcUse() {
SpringApplicationJsonEnvironmentPostProcessor springapplicationjsonenvironmentpostprocessor = new SpringApplicationJsonEnvironmentPostProcessor();
springapplicationjsonenvironmentpostprocessor.findPropertySource(null);
}
}