import org.springframework.boot.context.embedded.EmbeddedServletContainerCustomizerBeanPostProcessor;
public class FunctionUse788 {
public void funcUse() {
EmbeddedServletContainerCustomizerBeanPostProcessor embeddedservletcontainercustomizerbeanpostprocessor = new EmbeddedServletContainerCustomizerBeanPostProcessor();
embeddedservletcontainercustomizerbeanpostprocessor.postProcessBeforeInitialization(null);
}
}