import org.springframework.boot.env.SpringApplicationJsonEnvironmentPostProcessor;
public class FunctionUse1805 {
public void funcUse() {
SpringApplicationJsonEnvironmentPostProcessor springapplicationjsonenvironmentpostprocessor = new SpringApplicationJsonEnvironmentPostProcessor();
springapplicationjsonenvironmentpostprocessor.postProcessEnvironment(null,null);
}
}