import org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor;
public class FunctionUse465 {
public void funcUse() {
ConfigurationPropertiesBindingPostProcessor configurationpropertiesbindingpostprocessor = new ConfigurationPropertiesBindingPostProcessor();
configurationpropertiesbindingpostprocessor.getDefaultConversionService();
}
}