import org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor;
public class FunctionUse462 {
public void funcUse() {
ConfigurationPropertiesBindingPostProcessor configurationpropertiesbindingpostprocessor = new ConfigurationPropertiesBindingPostProcessor();
configurationpropertiesbindingpostprocessor.getSinglePropertySourcesPlaceholderConfigurer();
}
}