import org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessorRegistrar;
public class FunctionUse475 {
public void funcUse() {
ConfigurationPropertiesBindingPostProcessorRegistrar configurationpropertiesbindingpostprocessorregistrar = new ConfigurationPropertiesBindingPostProcessorRegistrar();
}
}