import org.springframework.boot.context.embedded.EmbeddedServletContainerCustomizerBeanPostProcessor;
public class FunctionUse789 {
public void funcUse() {
EmbeddedServletContainerCustomizerBeanPostProcessor embeddedservletcontainercustomizerbeanpostprocessor = new EmbeddedServletContainerCustomizerBeanPostProcessor();
embeddedservletcontainercustomizerbeanpostprocessor.postProcessAfterInitialization(null,null);
}
}