import org.springframework.boot.context.embedded.AbstractConfigurableEmbeddedServletContainer;
public class FunctionUse695 {
public void funcUse() {
AbstractConfigurableEmbeddedServletContainer abstractconfigurableembeddedservletcontainer = new AbstractConfigurableEmbeddedServletContainer();
abstractconfigurableembeddedservletcontainer.setRegisterDefaultServlet(null);
}
}