import org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext;
public class FunctionUse1179 {
public void funcUse() {
AnnotationConfigEmbeddedWebApplicationContext annotationconfigembeddedwebapplicationcontext = new AnnotationConfigEmbeddedWebApplicationContext();
annotationconfigembeddedwebapplicationcontext.setScopeMetadataResolver(null);
}
}