import org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor;
public class FunctionUse457 {
public void funcUse() {
ConfigurationPropertiesBindingPostProcessor configurationpropertiesbindingpostprocessor = new ConfigurationPropertiesBindingPostProcessor();
configurationpropertiesbindingpostprocessor.postProcessAfterInitialization(null,null);
}
}