import org.springframework.boot.context.embedded.AbstractConfigurableEmbeddedServletContainer;
public class FunctionUse709 {
public void funcUse() {
AbstractConfigurableEmbeddedServletContainer abstractconfigurableembeddedservletcontainer = new AbstractConfigurableEmbeddedServletContainer();
abstractconfigurableembeddedservletcontainer.isRegisterDefaultServlet();
}
}