import org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor;
public class FunctionUse455 {
public void funcUse() {
ConfigurationPropertiesBindingPostProcessor configurationpropertiesbindingpostprocessor = new ConfigurationPropertiesBindingPostProcessor();
configurationpropertiesbindingpostprocessor.postProcessBeforeInitialization(null,null);
}
}