import org.springframework.boot.type.classreading.ConcurrentReferenceCachingMetadataReaderFactory;
public class FunctionUse10 {
public void funcUse() {
ConcurrentReferenceCachingMetadataReaderFactory concurrentreferencecachingmetadatareaderfactory = new ConcurrentReferenceCachingMetadataReaderFactory();
concurrentreferencecachingmetadatareaderfactory.createMetadataReader(null);
}
}