import org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext;
public class FunctionUse1180 {
public void funcUse() {
AnnotationConfigEmbeddedWebApplicationContext annotationconfigembeddedwebapplicationcontext = new AnnotationConfigEmbeddedWebApplicationContext();
annotationconfigembeddedwebapplicationcontext.setEnvironment(null);
}
}