import org.springframework.boot.context.embedded.WebApplicationContextServletContextAwareProcessor;
public class FunctionUse734 {
public void funcUse() {
WebApplicationContextServletContextAwareProcessor webapplicationcontextservletcontextawareprocessor = new WebApplicationContextServletContextAwareProcessor();
webapplicationcontextservletcontextawareprocessor.getServletConfig();
}
}