import org.springframework.boot.type.classreading.ConcurrentReferenceCachingMetadataReaderFactory;
public class FunctionUse11 {
public void funcUse() {
ConcurrentReferenceCachingMetadataReaderFactory concurrentreferencecachingmetadatareaderfactory = new ConcurrentReferenceCachingMetadataReaderFactory();
concurrentreferencecachingmetadatareaderfactory.clearCache();
}
}