import org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainerFactory;
public class FunctionUse936 {
public void funcUse() {
UndertowEmbeddedServletContainerFactory undertowembeddedservletcontainerfactory = new UndertowEmbeddedServletContainerFactory();
undertowembeddedservletcontainerfactory.registerServletContainerInitializerToDriveServletContextInitializers(null,null);
}
}