import org.springframework.boot.context.embedded.AbstractConfigurableEmbeddedServletContainer;
public class FunctionUse718 {
public void funcUse() {
AbstractConfigurableEmbeddedServletContainer abstractconfigurableembeddedservletcontainer = new AbstractConfigurableEmbeddedServletContainer();
abstractconfigurableembeddedservletcontainer.getLocaleCharsetMappings();
}
}