import org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessorRegistrar;
public class FunctionUse476 {
public void funcUse() {
ConfigurationPropertiesBindingPostProcessorRegistrar configurationpropertiesbindingpostprocessorregistrar = new ConfigurationPropertiesBindingPostProcessorRegistrar();
}
}