import org.springframework.boot.context.embedded.AbstractConfigurableEmbeddedServletContainer;
public class FunctionUse688 {
public void funcUse() {
AbstractConfigurableEmbeddedServletContainer abstractconfigurableembeddedservletcontainer = new AbstractConfigurableEmbeddedServletContainer();
abstractconfigurableembeddedservletcontainer.shouldRegisterJspServlet();
}
}