import org.springframework.boot.type.classreading.ConcurrentReferenceCachingMetadataReaderFactory;
public class FunctionUse9 {
public void funcUse() {
ConcurrentReferenceCachingMetadataReaderFactory concurrentreferencecachingmetadatareaderfactory = new ConcurrentReferenceCachingMetadataReaderFactory();
concurrentreferencecachingmetadatareaderfactory.getMetadataReader(null);
}
}