import org.springframework.boot.context.embedded.AbstractConfigurableEmbeddedServletContainer;
public class FunctionUse699 {
public void funcUse() {
AbstractConfigurableEmbeddedServletContainer abstractconfigurableembeddedservletcontainer = new AbstractConfigurableEmbeddedServletContainer();
abstractconfigurableembeddedservletcontainer.setLocaleCharsetMappings(null);
}
}