import org.springframework.boot.context.embedded.EmbeddedServletContainerCustomizerBeanPostProcessor;
public class FunctionUse787 {
public void funcUse() {
EmbeddedServletContainerCustomizerBeanPostProcessor embeddedservletcontainercustomizerbeanpostprocessor = new EmbeddedServletContainerCustomizerBeanPostProcessor();
embeddedservletcontainercustomizerbeanpostprocessor.postProcessBeforeInitialization(null,null);
}
}