import org.springframework.boot.context.ConfigurationWarningsApplicationContextInitializer.ConfigurationWarningsPostProcessor;
public class FunctionUse1207 {
public void funcUse() {
ConfigurationWarningsPostProcessor configurationwarningspostprocessor = new ConfigurationWarningsPostProcessor();
configurationwarningspostprocessor.postProcessBeanDefinitionRegistry(null);
}
}