import org.springframework.boot.context.ConfigurationWarningsApplicationContextInitializer;
public class FunctionUse1193 {
public void funcUse() {
ConfigurationWarningsApplicationContextInitializer configurationwarningsapplicationcontextinitializer = new ConfigurationWarningsApplicationContextInitializer();
}
}